config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'documents#index'
  resources :documents
  resources :edits, only: [:show]
  # get '/edits/:id', to: 'edits#show', as: :edit_path
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
	has_many :edits
	has_many :users, through: :edits
	
	def is_available?
		return self.is_available
	end

	def is_available!
		self.is_available = true
		self.save
	end

	def is_not_available!
		self.is_available = false
		self.save
	end
end

app/models/edit.rb
class Edit < ApplicationRecord
	belongs_to :user
	belongs_to :document
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :edits
  has_many :documents, through: :edits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  include TextChange
  
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @edits = @document.edits.reverse
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    unless @document.is_available?
      respond_to do |format|
        format.html { redirect_to @document, notice: 'Document is currently unavailable for editing' }
        format.json { render json: {error: 'Document is currently unavailable for editing'}, status: :unprocessable_entity }
      end
    else
      @document.is_not_available!
    end
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    old_text = @document.text
    new_text = params[:document][:text]
    @change = text_change old_text, new_text
    
    unless @change[:result] == 'no change'
      edit_params = @change[:result]
      edit_params[:document_id] = @document.id
      edit_params[:user_id] = current_user.id.to_i
    end

    respond_to do |format|
      if @document.update(document_params)
        @edit = Edit.create(edit_params) unless @change[:result] == 'no change'
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end

    @document.is_available!
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.fetch(:document).permit(:title, :text)
    end
end

app/controllers/edits_controller.rb
class EditsController < ApplicationController
	before_action :authenticate_user!
  before_action :set_edit, only: [:show]
	include GetText
	
	def show
		@text = get_text_from @edit
		@document = @edit.document
	end

	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_edit
	    @edit = Edit.find(params[:id])
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/edits_helper.rb
module EditsHelper
end

app/views/documents/_form.html.erb
<%= form_for(document) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<div class="row">
	<div class="col s12 m3"></div>
	<%= form_for @document, html: {class: 'col s12 m6'} do |f| %>

		<div class="row">
			<div class="input-field col s12">
	  		<%= f.text_area :text, class: 'materialize-textarea' %><br />
	  	</div>
	  </div>

	  <%= f.submit 'Update Document', class: 'btn' %>
	<% end %>
</div>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<% i=1 %>
<div class="row">
<% @documents.each do |document| %>
  <div class="col m4 s12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= document.title %></span>
          <p>
            <%= document.text[0..45] %>
            <%if document.text.length > 45 %>...<%end%>
          </p>
      </div>
      <div class="card-action">
        <%= link_to 'Show', document %>
        <%= link_to 'Edit', edit_document_path(document) %>

        <% if document.edits.size > 0%>
          <a class='dropdown-button btn' data-beloworigin="true" data-activates=<%='dropdown'+i.to_s%> >View Edit History</a>

          <ul id=<%='dropdown'+i.to_s%> class='dropdown-content'>
          <% document.edits.reverse.each do |edit| %>
              <li><%= link_to edit.user.email, edit%></li>
          <% end %>
          </ul>
        <% else %>
          <a class='dropdown-button btn'>No Edit History</a>
        <% end %>
      </div>
    </div>
  </div>
  <%i=i+1%>
<%end%>
</div>
<br>

<%= link_to 'New Document', new_document_path, class: 'btn' %>

app/views/documents/new.html.erb
<h1>New Document</h1>
<div class="row">
	<div class="col s12 m3"></div>
	<%= form_for @document, html: {class: 'col s12 m6'}  do |f| %>
		<div class="row">
			<div class="input-field col s12">
	  		<%= f.text_field :title, placeholder: 'Title' %><br />
	  	</div>
		</div>

		<div class="row">
			<div class="input-field col s12">
	  		<%= f.text_area :text, class: 'materialize-textarea', placeholder: 'Text' %><br />
	  	</div>
		</div>

	  <%= f.submit 'Create Document', class: 'btn' %>
	<% end %>
</div>
<%= link_to 'Back', documents_path, class: 'btn' %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @document.title %></span>
          <p>
            <%= @document.text %>
          </p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_document_path(@document) %>

        <% if @document.edits.size > 0%>
          <a class='dropdown-button btn' data-beloworigin="true" data-activates=<%='dropdown_doc_edit'+@document.id.to_s%> >View Edit History</a>

          <ul id=<%='dropdown_doc_edit'+@document.id.to_s%> class='dropdown-content'>
          <% @document.edits.reverse.each do |edit| %>
              <li><%= link_to edit.user.email, edit%></li>
          <% end %>
          </ul>
        <% else %>
          <a class='dropdown-button btn'>No Edit History</a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/edits/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @document.title %></span>
          <p>
            <%= @text %>
          </p>
      </div>
      <div class="card-action">
        <%= link_to 'Back', @document %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocEditing</title>
    <% if user_signed_in? %>
      <%= link_to('Home', root_path, class: 'btn') %>
      <%= link_to('Logout', destroy_user_session_path, class: 'btn', method: :delete) %>        
    <% end %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
              
  </head>

  <body>
    <%= yield %>
  </body>
</html>